sonar.projectKey=pointedsec_point-my-auth
sonar.organization=pointedsec
sonar.host.url=https://sonarcloud.io

# Source
sonar.sources=point-my-auth-core/src/main/java
sonar.tests=point-my-auth-core/src/test/java

# Java
sonar.java.source=21
sonar.java.target=21

# Encoding
sonar.sourceEncoding=UTF-8

# JaCoCo coverage
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/generated/**
